
services:
  app:
    build: .
    container_name: zippy_app
    ports:
      - "8005:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    gpus: all

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_llava
    ports:
      - "11445:11434"
    volumes:
      - ollama_data:/root/.ollama

    gpus: all


volumes:
  ollama_data: {}